name: map-update-to-the-appropriate-lambda_function
# on:
#   push:
#     paths:
#       - '**/lambda_function_1/**'
on: [push]
jobs:
  map-commit-to-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test echo command
        run: |
          echo "very soon an aws command will run \
          in place of this echo command.."
      - name: checking around and within the working directory
        run: |
          pwd
          ls $(pwd)

      - name: putting last modified file paths in a variable
        run: echo "modded_paths=$(git diff --name-only -r HEAD^1 HEAD)" >> $GITHUB_OUTPUT
      
      - name: echoing variable storing last modified file paths
        run: |
          echo ${{ env.modded_paths }}
        