name: map-update-to-the-appropriate-lambda_function
# on:
#   push:
#     paths:
#       - '**/lambda_function_1/**'
on: [push]
jobs:
  map-commit-to-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "very soon an aws command will run \
          in place of this echo command.."
      - run: |
          pwd
          ls $(pwd)