name: map-update-to-the-appropriate-lambda_function
# on:
#   push:
#     paths:
#       - '**/lambda_function_1/**'
on: [push]
jobs:
  map-commit-to-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: test echo command
        run: |
          echo "very soon an aws command will run \
          in place of this echo command.."
      - name: checking around and within the working directory
        run: |
          pwd
          ls $(pwd)
      
      - name: show branch
        run: git branch --show

      - name: putting last modified file paths in a variable
        run: echo "modded_paths=$(git diff --name-only -r ${{ github.event.after }} ${{ github.event.before }})" >> $GITHUB_ENV
      
      - name: echoing variable storing last modified file paths
        run: |
          for name in ${{ env.modded_paths }}; do
            if [[ $name =~ lambda_function\.py$ ]]; then
                echo $name | rev | cut -d "/" -f 2 | rev
            fi
          done
        